Clean up output and usage description

diff --git a/runrerun/runrerun b/runrerun/runrerun
--- a/runrerun/runrerun
+++ b/runrerun/runrerun
@@ -1,35 +1,60 @@
 #!/bin/sh
 
+self() {
+    basename $0
+}
+
 show_usage_and_exit() {
-echo "Utilty for launching and subsequently re-launching by remote trigger
-This is particularly useful for restarting servers during development
+echo "Utilty for launching and subsequently re-launching commands by remote trigger
+This is particularly useful for restarting servers during development, or
+setting up global hotkeys for triggering commands.
 
 EXAMPLE USAGE:
-    # begin
-    $0 -b FOO ./foo.sh
-    # restart
-    $0 -r FOO
+    # Example: Running a script, and retriggering it from wherever
+    $(self) --begin=FOO ./bar.sh
+    $(self) --restart=FOO
+
+    # Example: Using a flag in CMD
+    $(self) --begin=FOO './bar.sh --baz'
+
+    # Example: Escaping flags in CMD using --
+    $(self) --begin=FOO -- ./bar.sh --baz
+
+    # Example: Specifying kill-method
+    $(self) --begin=FOO --kill-method=nice-kill ./bar.sh
+    $(self) --restart=FOO
+
+    # Shorthand version:
+    $(self) -b FOO -k nice-kill ./bar.sh
+    $(self) -r FOO
 
 USAGE (init):
-    $0 (--begin=KEY | -b KEY) <CMD..>
-    $0 (--begin=KEY | -b KEY) (--kill-method=METHOD | -k METHOD) <CMD..>
+    $(self) --begin=KEY <CMD..>
+    $(self) (--begin=KEY | -b KEY) (--kill-method=METHOD | -k METHOD) <CMD..>
 
 USAGE (restart):
-    $0 (--restart=KEY | -r KEY)
+    $(self) (--restart=KEY | -r KEY)
 
 ARGUMENTS:
-    KEY         A user-defined key that must be shared between --begin and --restart stages
-                This is used to identify the process
-    METHOD      The method used to kill the running process
-                    term            - Sends a SIGTERM (default)
-                    kill            - Sends a SIGKILL
-                    int             - Sends a SIGINT
-                    hup             - Sends a SIGHUP
-                    double-int      - Sends two SIGINT, particularly useful for docker-compose
-                    nice-kill       - Sends a SIGTERM, SIGINT, SIGHUP and finally SIGKILL, in
-                                      that order, with a short 2 second delay between each.
-                                      Use this if you don't want to bother with figuring out which
-                                      would be best suited.
+    --begin=KEY,-b KEY      A user-defined key that must be shared between --begin and --restart
+                            stages. This is used to identify the process
+    --restart=KEY,-r KEY    Restarts a command started with --begin, with the same KEY
+    --kill-method=METHOD,   Specifies termination method. Used only with --beging. See details below
+               -k METHOD
+    --                      All arguments passed after the double-hyphen is considered part of CMD
+    <CMD>                   The command that is run on every re-run.
+
+METHOD:
+          The method used to kill the running process
+                term            - Sends a SIGTERM (default)
+                kill            - Sends a SIGKILL
+                int             - Sends a SIGINT
+                hup             - Sends a SIGHUP
+                double-int      - Sends two SIGINT, particularly useful for docker-compose
+                nice-kill       - Sends a SIGTERM, SIGINT, SIGHUP and finally SIGKILL, in
+                                    that order, with a short 2 second delay between each.
+                                    Use this if you don't want to bother with figuring out which
+                                    would be best suited.
 
 OPTIONS
     -h,--help       Show this help text
@@ -74,8 +99,18 @@ parse_arguments() {
                 kill_method=$(echo $1 | sed -e 's/^[^=]*=//g')
                 shift
                 ;;
+            -- )
+                pass_through=true
+                shift
+                cmd="$cmd $@"
+                break
+                ;;
             -*)
-                echo_error "Invalid flag: $1"
+                if [ "$cmd" ] ; then
+                    echo_error "Invalid flag: $1. If part of CMD, use '--' to escape arguments"
+                else
+                    echo_error "Invalid flag: $1"
+                fi
                 exit 1
                 ;;
             *)
@@ -90,32 +125,32 @@ tty_available() {
     [ -t 1 ]
 }
 
-GREEN='\033[0;32m'
-RED='\033[0;31m'
-RESET='\033[0m'
+if [ tty_available ] ; then
+    YELLOW='\033[1;33m'
+    GREEN='\033[0;32m'
+    RED='\033[0;31m'
+    RESET='\033[0m'
+else
+    YELLOW=''
+    GREEN=''
+    RED=''
+    RESET=''
+fi
 echo_error() {
-    if tty_available ; then
-        echo "${RED}ERROR${RESET} $@" 1>&2
-    else
-        echo "ERROR: $@" 1>&2
-    fi
+    echo "${RED}ERROR${RESET} $@" 1>&2
 }
 
 echo_info() {
-    if tty_available ; then
-        echo "${GREEN}$@${RESET}"
-    else
-        echo "$@"
-    fi
+    echo "${GREEN}$@${RESET}"
 }
 
 process_arguments() {
-    if [ -z "$begin_key" -a -z "$restart_key" ] ; then
+    if [ "$begin_key" -a "$restart_key" ] ; then
         echo_error "Either --begin=KEY or --restart=KEY must be set. See --help" ; exit 1
     fi
-    if [ ! -z "$begin_key" ] ; then
+    if [ "$begin_key" ] ; then
         BEGIN_KEY=${begin_key}
-        if [ -z "$cmd" ] ; then
+        if [ ! "$cmd" ] ; then
             echo_error "CMD must be set when in --begin mode. See --help" ; exit 1
         fi
         CMD="$cmd"
@@ -132,9 +167,9 @@ process_arguments() {
         fi
         KILL_METHOD="$kill_method"
     fi
-    if [ ! -z "$restart_key" ] ; then
+    if [ "$restart_key" ] ; then
         RESTART_KEY=${restart_key}
-        if [ ! -z "$kill_method" ] ; then
+        if [ "$kill_method" ] ; then
             echo_error "--kill-method=METHOD has effect only in --begin mode." ; exit 1
         fi
     fi
@@ -151,14 +186,14 @@ cleanup_interrupted() {
 }
 
 cleanup_common() {
-    if [ ! -z "${BEGIN_KEY}" ] ; then
+    if [ "${BEGIN_KEY}" ] ; then
         if [ -f "$(temporary_key_file)" ] ; then
             rm -- $(temporary_key_file)
         fi
-        if [ "$verbose_flag" = true ] ; then
+        if [ "$verbose_flag" ] ; then
             set +x
         fi
-        if [ ! -z "$CMD_PID" ] && is_process_alive $CMD_PID ; then
+        if [ "$CMD_PID" ] && is_process_alive $CMD_PID ; then
             terminate_cmd
         fi
     fi
@@ -192,13 +227,26 @@ run_artificial_wait_in_background() {
     tail -f /dev/null
 }
 
+# Needed because some shells provde built-in echo that
+# can cause issues from being non-posix compliant
+native_echo() {
+    $(which echo) "$@"
+}
+
+HAS_REACHED_END=
 CMD_PID=
 run_command_in_background() {
+    # Clear the current output line, which should only be the 'waiting' info
+    # line below, if has ever been printed
+    if [ "$HAS_REACHED_END" ] ; then
+        native_echo -en '\033[2K\r'
+    fi
     $@ &
     CMD_PID="$!"
     wait $CMD_PID
     # In the case of command actually terminating
-    echo_info "\n$CMD [DONE]. Waiting for reruns..."
+    echo -n "${YELLOW}Waiting for reruns...${RESET}"
+    HAS_REACHED_END=true
     run_artificial_wait_in_background &
     CMD_PID="$!"
     wait $CMD_PID
@@ -216,7 +264,6 @@ kill_process() {
         if is_process_alive $CMD_PID ; then
             sleep 0.1;
         else
-            echo "Process killed using $1"
             return 0;
         fi
     done
@@ -272,12 +319,12 @@ restart_request() {
 main() {
     parse_arguments "$@"
     process_arguments
-    if [ ! -z "$BEGIN_KEY" ] ; then
+    if [ "$BEGIN_KEY" ] ; then
         #   HANDLE INITIALIZATION
         generate_temporary_key_file
         run_command_in_background "$CMD"
         :
-    elif [ ! -z "$RESTART_KEY" ] ; then
+    elif [ "$RESTART_KEY" ] ; then
         #   SEND RESTART SIGNAL TO INTITIALIZING PROCESS
         if [ ! -f "$(temporary_key_file)" ] ; then
             echo_error "Could not find matching process with KEY=$KEY Terminating" ; exit 1
@@ -292,4 +339,3 @@ main() {
 }
 
 main "$@"
-
